"""
tests/test_integration_p1_p2.py — End-to-End Integration Test: Person 1 -> Person 2

Verifies:
1. Real chunks generated by Person 1 (output/chunks.json or output/backup_chunks.json)
   load cleanly into Person 2's CodebaseRetriever.
2. Vector dimensions match strictly (3072-dim for Gemini or 384-dim for local).
3. Search ranking produces semantically accurate top-k results matching the contract
   expected by Person 3 (/ask LLM endpoint).
4. Any vector dimension mismatch immediately raises a clear ValueError instead of
   silently truncating.
"""

import os
import sys
from pathlib import Path

# Force UTF-8 output on Windows
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if sys.stderr.encoding and sys.stderr.encoding.lower() != "utf-8":
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# Ensure root directory and retrieval_storage_2 are on sys.path
ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))
sys.path.insert(0, str(ROOT_DIR / "retrieval_storage_2"))

try:
    from dotenv import load_dotenv
    load_dotenv(ROOT_DIR / ".env")
except ImportError:
    pass

from retrieval_storage_2.retrieval import (
    CodebaseRetriever,
    EmbeddingProvider,
    _pure_cosine_similarity,
    cosine_similarity,
    init_retriever,
    search,
)


def test_real_chunks_loading_and_schema():
    """Verify Person 1's real chunks.json loads into Person 2 with 3072-dim embeddings."""
    click_path = ROOT_DIR / "output" / "chunks.json"
    backup_path = ROOT_DIR / "output" / "backup_chunks.json"

    target_path = click_path if click_path.exists() else backup_path
    assert target_path.exists(), f"Neither {click_path} nor {backup_path} exists! Run pipeline first."

    print(f"\n[Test] Testing loading against real Person 1 output: {target_path.name}")
    retriever = CodebaseRetriever()
    retriever.load_storage(str(target_path))

    assert len(retriever.chunks) > 0, "No chunks loaded into retriever"
    print(f"  ✓ Successfully loaded {len(retriever.chunks)} chunks into CodebaseRetriever")

    # Verify embeddings are present and 3072-dim
    dim_set = set()
    for chunk in retriever.chunks:
        assert chunk.embedding is not None, f"Chunk {chunk.chunk_id} in {chunk.file_path} missing embedding"
        assert isinstance(chunk.embedding, list), f"Chunk {chunk.chunk_id} embedding is not a list"
        dim_set.add(len(chunk.embedding))

    assert dim_set == {3072}, f"Expected 3072-dim embeddings, found dimensions: {dim_set}"
    print(f"  ✓ All {len(retriever.chunks)} chunks verified with strictly 3072-dim float vectors")


def test_search_retrieval_accuracy():
    """Verify semantic search ranking on real chunks returns accurate results matching Person 3 contract."""
    click_path = ROOT_DIR / "output" / "chunks.json"
    backup_path = ROOT_DIR / "output" / "backup_chunks.json"
    target_path = click_path if click_path.exists() else backup_path

    retriever = init_retriever(str(target_path))
    is_click = "chunks.json" == target_path.name

    query = "where is the command decorator defined?" if is_click else "where is URL safe serialization implemented?"
    print(f"\n[Test] Running semantic search query: {query!r}")

    results = search(query, top_k=5)
    assert len(results) > 0, "Search returned 0 results"
    assert len(results) <= 5, f"Search returned more than top_k results: {len(results)}"

    # Check Person 3 contract fields
    for r in results:
        assert "chunk_id" in r
        assert "file_path" in r
        assert "start_line" in r
        assert "end_line" in r
        assert "text" in r
        assert "similarity_score" in r
        assert isinstance(r["file_path"], str)
        assert isinstance(r["start_line"], int)
        assert isinstance(r["end_line"], int)
        assert isinstance(r["text"], str)
        assert isinstance(r["similarity_score"], float)

    print(f"  ✓ Top-1 Match: {results[0]['file_path']}:L{results[0]['start_line']}-L{results[0]['end_line']} (score: {results[0]['similarity_score']:.4f})")
    print(f"  ✓ Top-2 Match: {results[1]['file_path']}:L{results[1]['start_line']}-L{results[1]['end_line']} (score: {results[1]['similarity_score']:.4f})")

    # Semantic relevance check:
    if is_click:
        # Command decorator is in decorators.py or core.py
        relevant_files = [r["file_path"] for r in results[:3]]
        assert any("decorators.py" in f or "core.py" in f for f in relevant_files), \
            f"Expected decorators.py or core.py in top matches, got: {relevant_files}"
        print(f"  ✓ Verified semantic relevance: matched Click core/decorator modules!")
    else:
        relevant_files = [r["file_path"] for r in results[:3]]
        assert any("url_safe" in f or "serializer" in f for f in relevant_files), \
            f"Expected url_safe or serializer in top matches, got: {relevant_files}"
        print(f"  ✓ Verified semantic relevance: matched itsdangerous serializer modules!")


def test_dimension_mismatch_fails_loudly():
    """Verify that passing an incompatible dimension vector (e.g. 768 or 128) fails with ValueError."""
    print("\n[Test] Verifying dimension mismatch fails loudly and explicitly")
    v_3072 = [0.1] * 3072
    v_768 = [0.1] * 768

    # 1. Pure Python check
    try:
        _pure_cosine_similarity(v_768, v_3072)
        assert False, "Should have raised ValueError on 768 vs 3072 mismatch!"
    except ValueError as exc:
        assert "dimension mismatch" in str(exc).lower()
        print("  ✓ Pure Python cosine similarity raised ValueError on 768 vs 3072 mismatch")

    # 2. Vectorized check
    try:
        cosine_similarity(v_768, [v_3072])
        assert False, "Should have raised ValueError on 768 vs 3072 mismatch in numpy path!"
    except ValueError as exc:
        assert "dimension mismatch" in str(exc).lower()
        print("  ✓ Vectorized cosine similarity raised ValueError on 768 vs 3072 mismatch")


if __name__ == "__main__":
    print("=" * 70)
    print("PERSON 1 <-> PERSON 2 END-TO-END INTEGRATION TEST SUITE")
    print("=" * 70)
    test_real_chunks_loading_and_schema()
    test_search_retrieval_accuracy()
    test_dimension_mismatch_fails_loudly()
    print("\n" + "=" * 70)
    print("ALL INTEGRATION TESTS PASSED: Person 1 and Person 2 are 100% aligned!")
    print("=" * 70)
